### ISSUE TITLE
Import file not working

### ISSUE THREAD

**Issue by gpetho** [DEpt-metagenom/MetagenoMongo#17]
When I browse the sample test file from the original task issue and click the "Import file" button, nothing happens, the table containing the data in the csv file is not displayed.

**Comment by gpetho** [comment]
@iwmstjp , please check this, the application should be in a testable state on Wednesday.

**Comment by gpetho** [comment]
After copying the `.metagenomongo.csv` to `flask-version/metagenomongo` the fields are now displayed in the top line of the application, but the import file button still does nothing. After I browse `test_dept_sample_db.csv` from my computer and click on the button, nothing happens. The lines of the table are not displayed, and there is no error message.

**Comment by iwmstjp** [comment]
Could you run the app in the MetagenoMongo directory?
The run command will be
python flask-version/metagenomongo/app.py
I added the error handling for FileNotFoundError to the latest version.

**Comment by gpetho** [comment]
When I do that, I get a different error, which is (kind of as expected)
```
FileNotFoundError: [Errno 2] No such file or directory: 'uploads\\test_dept_sample_db.csv'
```
The root directory of the repository doesn't have an uploads subdirectory, which makes sense, that subdirectory belongs to the Flask application.

**Comment by iwmstjp** [comment]
Thank you for your reply.
I added uploads directory in the root directory.

**Comment by gpetho** [comment]
> I added uploads directory in the root directory.

Right, that's obviously a workaround, but we don't want to do that.  As I said, that subdirectory belongs to the Flask application, it has no business being in the root directory of the repository. Just to test what happens if I create an uploads directory in the root directory, I created one on my machine now, it doesn't change anything. Obviously the FileNotFoundError disappears, but the behavior doesn't change. The name of the selected file disappears and changes back to "No file selected.", the table is still empty, there is no error message or anything in the terminal.

**Comment by iwmstjp** [comment]
[sample.csv](https://github.com/user-attachments/files/16727863/sample.csv)
Could you try importing this file?

**Comment by gpetho** [comment]
That seems to work, it import this:

![image](https://github.com/user-attachments/assets/98f6d6f0-370f-404c-9779-fafbe2e3f008)

**Comment by iwmstjp** [comment]
Could you share your previous file which can not be imported?

**Comment by gpetho** [comment]
[test_dept_sample_db.csv](https://github.com/user-attachments/files/16728006/test_dept_sample_db.csv)

**Comment by gpetho** [comment]
This issue was resolved by the following commits:
[fix: add uploads directory in root directory](https://github.com/DEpt-metagenom/MetagenoMongo/commit/15d451b039a9c379bf7c55eb36cd14223713d134)
[fix: change file name format because : in a file path somtime makes errors](https://github.com/DEpt-metagenom/MetagenoMongo/commit/e8613452c3c2ea2a869275870f6da45711f7eb87)
[fix: add error handling for FileNotFoundError](https://github.com/DEpt-metagenom/MetagenoMongo/commit/814f5ddff0bf6cca04808e35df32052b0f70be88)

**Comment by iwmstjp** [comment]
This issue was resolved by the following commits:
[fix: add error message to index.html](https://github.com/iwmstjp/MetagenoMongo/commit/8a32e5c62d4f1f6794905d72da01021b8ed7e865)
[chore: add README.md](https://github.com/iwmstjp/MetagenoMongo/commit/7dd862ba69d1e333f525888905a36541a05fd97e)
[fix: add error handling for FileNotFoundError](https://github.com/iwmstjp/MetagenoMongo/commit/814f5ddff0bf6cca04808e35df32052b0f70be88)
