### ISSUE TITLE
Description for the .metagenomongo.csv file

### ISSUE THREAD

**Issue by haalasz** [DEpt-metagenom/MetagenoMongo#2]
# Role

The [.metagenomongo.csv](https://github.com/DEpt-metagenom/MetagenoMongo/blob/main/.metagenomongo.csv) file is a crucial component of the [metagenomongo.py](https://github.com/DEpt-metagenom/MetagenoMongo/blob/main/metagenomongo.py) script. This file enables us to define various input types without the need for code editing. It distinguishes between multiple types of input, including non-writable textbox, writable textbox, non-writable combobox, and writable combobox.

# Structure

1. Column 1 (Header Name) - The column names.

2. Column 2 (Data Type) - Specifies the type of data contained within the column. **[NOT USED]**

3. Column 3 (Options) - Indicates potential options or values that the column may contain.

4. Column 4 (Type) - Differentiates between fixed and dynamic columns.

# Usage

- Non-writable textbox (e.g. _id) - `_id,string,,fix` - This type of data should not be edited by the user.

- Writable textbox (e.g. projectID) - `projectID,string,,dynamic` -  Users can input data into this type of textbox.

- Non-writable combobox (e.g. source_type) - `source_type,string,"Human,Animal,Food,Environmental,Other,Missing,Not applicable,Not collected,Not provided,",fix` - Users can select from predefined options in this combobox.

- Writable combobox (e.g. platform) - `platform,string,"Nanopore MinION,PacBio HiFi,Illumina MiSeq,Illumina NextSeq500,",dynamic` - Users can both select from predefined options and input their own data into this combobox.

**Comment by laczkol** [comment]
I think this should be part of the main documentation, i.e. I would move it to README.md.

**Comment by haalasz** [comment]
Added the description of .metagenomongo.csv to README.
