### ISSUE TITLE
Handle _id column

### ISSUE THREAD

**Issue by gpetho** [DEpt-metagenom/MetagenoMongo#21]
As we discussed in today's meeting, two situations need to be distinguished when a file is imported:
- One case is when the data was exported from the MongoDB by the administrators and they want to use the app to check the consistency of some rows of the table. In that case, the table contains an `_in` field (column). If there is an `_id` column, the user must be forbidden to edit it. I believe the correct way to do this is preferably to hide the `_id` field altogether by adding the `type="hidden"` attribute to the `input` fields that belong to the `_id` column in the table. If the table contains an `_id` field, the "Add new line" button should also be hidden, since in this special situation we can assume that the admins only want to validate and correct existing lines and not add further lines. Obviously, there is also the problem that we couldn't generate an `_id` for the new line anyway.
- The second case is that the csv or Excel table that is being imported does not come from the database. In that case it does not contain an `_id` column. We want it simply to import the table with the existing fields and not add an `_id` field to it at all, neither when it is opened, nor when it is saved.

**Comment by iwmstjp** [comment]
This issue was resolved by the following commits:
[feature: make _id columuns not editable](https://github.com/iwmstjp/MetagenoMongo/commit/fec5e3647a5ac18096e946d4ce2635e1e6d1bdee)
[fix: make _id unaddable in the frontpage.](https://github.com/iwmstjp/MetagenoMongo/commit/dfc16af12ccc758d9485d520ef78434db59e52d1)

**Comment by iwmstjp** [comment]
_id should be omitted if the data does not have _id column
