### ISSUE TITLE
Rework the Excel "import" function

### ISSUE THREAD

**Issue by haalasz** [DEpt-metagenom/MetagenoMongo#3]
NoneType errors, datetime library is not imported, empty cells are filled with None.

**Comment by albertbokor-unideb** [comment]
when importing  [this example file](https://github.com/user-attachments/files/15792634/mongodb_template_ver2_NNcsajkok.xlsx), puts 4 more records filled with `None`

**Comment by albertbokor-unideb** [comment]
> empty cells are filled with None
how do we want it to behave instead?

**Comment by haalasz** [comment]
> > empty cells are filled with None
> 
> how do we want it to behave instead?

If the cell is empty in the xlsx file, it must remain empty after import.

**Comment by albertbokor-unideb** [comment]
handling excel column name mismatch (not to import but error out)

**Comment by haalasz** [comment]
After importing xlsx with wrong column name (not matching the .metagenomongo.csv) it gives this error message after clicking the popup to fix the wrong name (based on difflib):

```
/home/haalasz/anaconda3/lib/python3.11/site-packages/openpyxl/reader/excel.py:228: UserWarning: Data Validation extension is not supported and will be removed
  ws_parser.bind_all()
Traceback (most recent call last):
  File "/home/haalasz/github/metagenom/MetagenoMongo/metagenomongo.py", line 267, in <module>
    if cell_value.strip():
       ^^^^^^^^^^^^^^^^
AttributeError: 'datetime.datetime' object has no attribute 'strip'
```

**Comment by albertbokor-unideb** [comment]
TODO: see if i can find a good existing xlsx to csv tool that can be imported to execute before excel import

TODO EXTRA: popup to veriyf/select table from excel file

**Comment by albertbokor-unideb** [comment]
TODO:  swap file import to pandas, if doen't work this https://github.com/dilshod/xlsx2csv

**Comment by albertbokor-unideb** [comment]
> If the cell is empty in the xlsx file, it must remain empty after import.

added conversion for this on each place it imports the file

**Comment by gpetho** [comment]
I've just noticed that there's a draft pull request on this repo that is related to this issue. What is the status of that pull request? Is it something that should be merged into the main branch?

**Comment by haalasz** [comment]
I've commented on the pull request that the excel import fix messed up the GUI. It is fixed now and the working app is called 'mtgnmng.py' to avoid the accidental merge. The xlsx fix branch should not be merged with the main.

**Comment by gpetho** [comment]
Thank you, I have closed the pull request as rejected.
