### ISSUE TITLE
Bad request error when file is missing

### ISSUE THREAD

**Issue by laczkol** [DEpt-metagenom/MetagenoMongo#32]
When I click on "Import file" with the correct user name entered, but do not upload a file, I get a "Bad Request" error message. I imagine some of the future users may not know if it's an error on their end or on the applications end, which could lead to confusion. I think it would be nice to warn the user about the missing file, similar to the text box that appears when the username is missing. I get the same error using both Brave browser v 1.68.137 and Firefox 115.14.0esr, so I assume this is the general behavior when the file is missing.

**Comment by gpetho** [comment]
@laczkol Just to understand what is going on here: why would anybody click on "Import file" but then not upload a file?

**Comment by gpetho** [comment]
To answer my own question, it might not be immediately obvious to the user that they first need to select a file to be imported using the browse button and can only import after that. @iwmstjp please implement a check similar to the `user_name` check. If a file has not been selected, the import button should output a message that a file must be selected first.

**Comment by iwmstjp** [comment]
I fixed this problem.

**Comment by laczkol** [comment]
> I fixed this problem.

The feature seems to work well.
