### ISSUE TITLE
There should only be one `user_name` field, not two

### ISSUE THREAD

**Issue by gpetho** [DEpt-metagenom/MetagenoMongo#33]
Please remove one of the two `user_name` fields. Both the "Import file" and the "Add new line" buttons should check this one field. It simply doesn't make any sense to have two.

**Comment by iwmstjp** [comment]
I solved this one.
[fix: remove one of the two user_name input field](https://github.com/iwmstjp/MetagenoMongo/commit/aa71ef491df6ddb2f19949deca3946519fbdd0d3)
