### ISSUE TITLE
Table and notification areas on page should be of set size with vertical scroll bars

### ISSUE THREAD

**Issue by haalasz** [DEpt-metagenom/MetagenoMongo#34]
When working with larger tables, users currently need to scroll vertically to access the horizontal scrollbar. This can cause difficulties, as users cannot see the column headers while navigating horizontally, which is particularly problematic when data needs to be filled in or checked.

Display a fixed number of rows (e.g., 10 rows) in the table at a time. This would allow users to navigate horizontally without losing sight of the column headers, improving the ease of use and overall user experience.

**Comment by gpetho** [comment]
On the table display page there should be two areas of set size. Below the header the rest of the browser window should be split into two vertical regions about 2/3 and 1/3 height of the window (i.e. about 1/2 and 1/4 of the whole window height, the remaining about 1/4 occupied by the header). The larger region that is placed higher should contain the table. This region should have both a horizontal scroll bar, which is already there, and a vertical scroll bar. The table should have a header containing the column names, which is already there, and this header should remain always visible when the vertical scroll bar is used, and it should always display the names of the columns below when the horizontal scroll bar is used.
The region that is placed below the table should contain the validation error messages. This should also be a vertically scrollable text area. It should not be horizontally scrollable but break lines that are too long.

**Comment by iwmstjp** [comment]
I added vertical scrollbars.
[style: add vertical scrollbar.](https://github.com/iwmstjp/MetagenoMongo/commit/b08b884fc646a503579e0734557c486cea8d089c)
[style: add vertical scrollbar to the result part.](https://github.com/iwmstjp/MetagenoMongo/commit/4c28c014679ff7d55ee7394e3cb6cf7e88a8d327)
