### ISSUE TITLE
Rework the "correct" function

### ISSUE THREAD

**Issue by haalasz** [DEpt-metagenom/MetagenoMongo#4]
Function review and full rework needed.

**Comment by laczkol** [comment]
Please detail this bug report.
Provide a brief description of the bug, if any, outline the steps required to reproduce the error, describe the expected and actual behavior, and provide additional context (e.g. environment, time of first occurrence of the bug...). The first step to solving the issue would be to reproduce errors for which these details are needed.

**Comment by albertbokor-unideb** [comment]
crashes out from .xlsx import
