### ISSUE TITLE
Jump to table row referenced in error message

### ISSUE THREAD

**Issue by gpetho** [DEpt-metagenom/MetagenoMongo#40]
The error messages should be made clickable. When a user clicks on an error message, the table should jump to that row, i.e. in the scrollable table above the first row should be the row to which the error message refers. For example, if the error occurs in row 17, then when the user clicks on this error message, the table above should jump to row 17 and the rows after it. When the error message concerns more than one row, then the row numbers should be made clickable instead of the whole message.

**Comment by iwmstjp** [comment]
I solved this part.
[feature: add jump a table row referenced in the error message](https://github.com/iwmstjp/MetagenoMongo/commit/bce9e7576b00aaaf76ab0c50898817937159366f)
