### ISSUE TITLE
Remove end-of-line semicolons

### ISSUE THREAD

**Issue by haalasz** [DEpt-metagenom/MetagenoMongo#43]
The original application removed unnecessary end-of-line semicolons when processing data, but this behavior is missing in the web application.

I recently checked a table where the cells in the comment column had end-of-line semicolons that were not removed, either during the file upload or when the table was saved.

**Comment by gpetho** [comment]
I don't understand what end-of-line semicolons are, except when we are talking about code written in C, Java or something like that. I wouldn't expect them to occur in a csv file. Please provide an example file to test the solution on. Why is it a problem if a comment contains a semicolon at the end of its lines?

**Comment by haalasz** [comment]
After some time to think, I came to the conclusion that since it is not a common case, this proposal is not important and the issue can be closed.
